#!/usr/bin/env python

import rospy
import time
import random
from gazebo_msgs.msg import ModelState, ModelStates
from geometry_msgs.msg import Pose
from geometry_msgs.msg import Twist

class Combination():
    def __init__(self):
        self.pub_model = rospy.Publisher('gazebo/set_model_state', ModelState, queue_size=1)
        self.moving()

    def moving(self):
        while not rospy.is_shutdown():
            model = rospy.wait_for_message('gazebo/model_states', ModelStates)
            for i in range(len(model.name)):
                    if model.name[i] == 'turtlebot3_burger':
                        turtlebot_pos= ModelState()
                        turtlebot_pos.model_name=model.name[i]
                        turtlebot_pos.pose = model.pose[i]
                        if turtlebot_pos.pose.position.x < 0.03 and turtlebot_pos.pose.position.y < 0.03:
                            print("ja<0.03")
                            for j in range(len(model.name)):
                                if model.name[j] == 'wall_6':
                                    print ("wall_6")
                                    wall_pos1= ModelState()
                                    wall_pos1.model_name=model.name[j]
                                    wall_pos1.pose = model.pose[j]
                                    b=random.randint(1, 2)
                                    print(b)
                                    if b==1:
                                        wall_pos1.pose.position.x = -0.5
                                        wall_pos1.pose.position.y = 0
                                    elif b==2:
                                        wall_pos1.pose.position.x = 1.5
                                        wall_pos1.pose.position.y = 0
                                    print(wall_pos1.pose.position.x)
                        self.pub_model.publish(wall_pos1)
                        rospy.sleep(1)

def main():
    rospy.init_node('simulation_5_obstacle_1')
    try:
        combination = Combination()
    except rospy.ROSInterruptException:
        pass

if __name__ == '__main__':
    main()
